### ISSUE TITLE
Visual Studio Importer shows no projects when selecting a solution

### ISSUE THREAD

**Issue by hilts-vaughan** [consulo/consulo-visual-studio#2]
Hi,

When I select a solution file in the importer, the box below it is is empty. 
![cap](https://cloud.githubusercontent.com/assets/1079207/14503071/682b7136-017c-11e6-961f-ae6fdf56530a.png)

Is this normal? Does this work yet? I can't seem to run anything when continuing anyway.

Latest version of everything.

**Comment by VISTALL** [comment]
Hi. It's not unity project?

**Comment by VISTALL** [comment]
Microsoft .NET or Mono .NET plugin installed?

**Comment by hilts-vaughan** [comment]
@No, not a Unity project. It's just a normal, Visual Studio 2013 project. Are those maybe not supported yet?

Microsoft .NET and Mono are both installed. I have attached the SLN as a TXT file.

[UnlinkMKV-GUI.TXT](https://github.com/consulo/consulo-visual-studio/files/217689/UnlinkMKV-GUI.TXT)

**Comment by hilts-vaughan** [comment]
Hi,

The importer version is "1066" and has a button that says "Update". I installed today,  but I hit update anyway but then it restarts, and an update is still available.

Maybe it's an outdated plugin issue? Why is the plugin not updating?

EDIT: Seems like that's the latest version according to Vulcan anyway.

**Comment by VISTALL** [comment]
Its a bug - when consulo build is old

**Comment by hilts-vaughan** [comment]
Hi,

My Consulo Build is 1318. I can file a new bug for this for you if you want. It may be unrelated.

**Comment by VISTALL** [comment]
You have installed plugins ? Microsoft or Mono?

**Comment by hilts-vaughan** [comment]
![plugins](https://cloud.githubusercontent.com/assets/1079207/14505185/0f42d6f4-0186-11e6-8376-bd2f74328b48.png)

**Comment by hilts-vaughan** [comment]
(Arch Linux)

**Comment by VISTALL** [comment]
You have project with .sln extension ?  (can you provide some example or project structure)

**Comment by hilts-vaughan** [comment]
You may clone this project, it is open source: https://github.com/hilts-vaughan/UnlinkMKV-GUI

SLN here: https://github.com/hilts-vaughan/UnlinkMKV-GUI/blob/master/UnlinkMKV-GUI/UnlinkMKV-GUI.sln

**Comment by VISTALL** [comment]
Thanks

**Comment by VISTALL** [comment]
Hi current implementation is very poor. If you interest - i will make it more powerful

**Comment by hilts-vaughan** [comment]
It would make it very viable for developers coming from Windows -- can I help at all?

**Comment by VISTALL** [comment]
After some time - try to update Visual Studio plugin.

Then try to import .sln project(and select Mono)

After import, open Project Structure and choose Mono SDK.

![image](https://cloud.githubusercontent.com/assets/542934/14507056/a05cf776-01c9-11e6-847c-94fc63adabf4.png)

It's a bug with SDK select, i will fix it in near future

**Comment by VISTALL** [comment]
Funny project - i found two bugs in C# implementation :)

**Comment by hilts-vaughan** [comment]
Hi,

Updated plugin. It still does not show -- do I need to setup the frameworks?

**Comment by VISTALL** [comment]
Hm. Maybe it's a bug on linux

**Comment by hilts-vaughan** [comment]
Hi,

Import empty -- however, creating manually like you show above works.

You said the import screen is a bug -- will fix later?

**Comment by VISTALL** [comment]
Working on fix(i need to restore my virtual machines, due yesterday i reinstalled windows)

**Comment by hilts-vaughan** [comment]
OK,

is working but can't compile w/o adding System.Drawing as well and System.Data.

I can add those in project structure?

**Comment by VISTALL** [comment]
yes. go to project structure - dependencies - PLUS (green plus button) - Standard Library - and select correct

**Comment by hilts-vaughan** [comment]
Awesome, it compiles now. I would reccomend adding `System.Core` as a default as well, since Visual Studio has a habit of adding `using System.Linq` on the top of every file, even if not used. Some projects have that and will not compile without it.

Maybe once SDK support is working import wizard can import all dependencies... cool :)

Thank you!

**Comment by VISTALL** [comment]
You can saw bug with **base** call - i known about it

**Comment by VISTALL** [comment]
And - yeah repeated.

**Comment by hilts-vaughan** [comment]
Excellent. If you need anything from me, please let me know.

**Comment by VISTALL** [comment]
Fixed. But - it only fix this problem

**Comment by hilts-vaughan** [comment]
You're great - thank you.

**Comment by VISTALL** [comment]
Problem with sdk select exists, i will fix it in near future

**Comment by VISTALL** [comment]
And be care - it's only VS importer, exporting is not implemented
